name: demo
on:
  push:
    branches:
      - main
    paths:
      - "/github/workflows/**"
      - "src/**"
      - "public/**"
      - "routes/**"
      - "views/**"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan "42.194.247.201" >> ~/.ssh/know_hosts
      - name: deploy
        run: |
          ssh -t -t root@42.194.247.201;
          git pull origin main;
          docker-compose down;
          docker-compose build naruto-server;
          docker-compose up -d;
